controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

notification_bundle:
    resource: '@NotificationBundle/config/routes.yaml'
